project_name: forge-downloader
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
archives:
- replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Commit }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
scoop:
  bucket:
    owner: itzg
    name: scoop-bucket
  license: MIT
  description: A simple utility for downloading Forge installers