version: 2

defaults: &defaults
  docker:
    - image: circleci/golang:1.12.4

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ arch }}-{{ .Branch }}-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "go.sum" }}
          paths:
            - /go/pkg

      - run: go test -mod=readonly

  release:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: goreleaser
          command: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  main:
    jobs:
      - build

  release:
    jobs:
      - release:
          filters:
            tags:
              only: /\d+(\.\d+)*(-.*)*/
            branches:
              ignore: /.*/